FROM scratch
MAINTAINER The CentOS Project <cloud-ops@centos.org>
ADD c7-docker.tar.xz /
LABEL name="CentOS Base Image" \
    vendor="CentOS" \
    license="GPLv2" \
    build-date="2016-02-17"

RUN yum install -y which  curl gcc-c++ patch readline readline-devel zlib zlib-devel libyaml-devel libffi-devel openssl-devel make  bzip2 autoconf automake libtool bison iconv-devel sqlite-devel
WORKDIR /root
RUN source ~/.bash_profile
RUN gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
RUN curl -L get.rvm.io | bash -s stable 
RUN source /etc/profile.d/rvm.sh


RUN mkdir /root/wordpress-rpm
RUN /usr/local/rvm/bin/rvm install 2.1.8
RUN /usr/local/rvm/bin/rvm use 2.1.8 --default
RUN bash --login
RUN /usr/bin/gem install fpm

WORKDIR /root/wordpress-rpm

RUN wget https://wordpress.org/latest.tar.gz

RUN tar -xzvf latest.tar.gz

ADD  wp-config.php /root/wordpress-rpm/

#fpm -s dir -t rpm -n {PACKAGE_NAME} -v   `` -C  /root/wordpress-rpm/  --prefix={INSTALL_LOCATION}
fpm -s dir -t rpm -n wordpress -v   4.4.2 -C /root/wordpress-rpm/ --prefix=/var/www/html1



# Volumes for systemd
# VOLUME ["/run", "/tmp"]

# Environment for systemd
# ENV container=docker

# For systemd usage this changes to /usr/sbin/init
# Keeping it as /bin/bash for compatability with previous
CMD ["/bin/bash"]
